# Decision Tree

A decision tree is a supervised machine learning algorithm used for both classification and regression tasks. It's a flowchart-like structure where each internal node represents a "test" on an attribute (e.g., whether a feature is less than a certain value), each branch represents the outcome of the test, and each leaf node represents a class label or a numerical value. Decision trees are particularly popular because they are easy to understand and interpret.

***Where to use decision trees***:
1. **Classification**: Decision trees are commonly used for classification tasks where the goal is to predict the category or class label of a new instance. For example, classifying whether an email is spam or not spam.
2. **Regression**: Decision trees can also be used for regression tasks, where the goal is to predict a continuous value. For example, predicting house prices based on features such as area, number of bedrooms, etc.
3. **Feature Selection**: Decision trees can be used to identify the most important features in a dataset. Features that appear near the root of the tree are typically more important for predicting the target variable.
4. **Data Exploration**: Decision trees can help in understanding the underlying structure of the data by visualizing the decision-making process.

***Data requirements for decision trees***:
1. **Categorical and Numerical Data**: Decision trees can handle both categorical and numerical data types. They are versatile in this aspect.
2. **Preprocessed Data**: Data should be preprocessed, including handling missing values and encoding categorical variables into a numerical format if needed. Decision trees don't handle missing values internally, so they need to be addressed beforehand.
3. **Enough Data**: Decision trees can work well with small datasets, but they can also suffer from overfitting if the dataset is too small or noisy. Having enough data to represent the underlying structure of the problem is crucial.
4. **Balanced Data**: For classification tasks, having a balanced dataset (similar proportions of each class) is ideal. Imbalanced datasets might lead to biased models.
5. **Homogeneous Data**: Decision trees work best when the data is relatively homogeneous within each region defined by the splits. If there's a lot of variability within these regions, decision trees might not perform well.

## Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier

C:\Users\ALICOM4\AppData\Local\Temp\ipykernel_6624\161604410.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Import Dataset

In [12]:
df = pd.read_csv('D:\\Data Practice JN\\Pre-Processing\\Wrangled Data of Social Media Ads.csv')
df

Unnamed: 0  Gender       Age  EstimatedSalary  Purchased
0             0       0  2.944439        11.156065          0
1             1       0  3.610918         9.903488          0
2             2       1  3.258097        10.668955          0
3             3       1  3.610918        10.950807          0
4             4       0  2.944439        11.238489          0
..          ...     ...       ...              ...        ...
395         395       1  3.828641        10.621327          1
396         396       0  3.931826        10.043249          1
397         397       1  3.912023         9.903488          1
398         398       0  3.583519        10.404263          0
399         399       1  3.891820        10.491274          1

[400 rows x 5 columns]

In [13]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

Gender       Age  EstimatedSalary  Purchased
0       0  2.944439        11.156065          0
1       0  3.610918         9.903488          0
2       1  3.258097        10.668955          0
3       1  3.610918        10.950807          0
4       0  2.944439        11.238489          0

## Model Building

### Define Model Values

In [23]:
x = df[['Age', 'Gender']]
y = df[['Purchased']]

In [25]:
x.head()

Age  Gender
0  2.944439       0
1  3.610918       0
2  3.258097       1
3  3.610918       1
4  2.944439       0

In [26]:
y.head()

Purchased
0          0
1          0
2          0
3          0
4          0

### Train Test Split

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [30]:
model = DecisionTreeClassifier()
model.fit(x_train , y_train)

DecisionTreeClassifier()

In [31]:
x_train

Age  Gender
336  4.060443       0
64   4.077537       1
55   3.178054       1
106  3.258097       1
300  4.060443       1
..        ...     ...
323  3.871201       1
192  3.367296       0
117  3.583519       0
47   3.295837       1
172  3.258097       1

[320 rows x 2 columns]

In [32]:
y_train

Purchased
336          1
64           0
55           0
106          0
300          1
..         ...
323          1
192          0
117          0
47           0
172          0

[320 rows x 1 columns]

In [33]:
x_test

Age  Gender
132  3.401197       0
309  3.637586       1
341  3.555348       0
196  3.401197       1
246  3.555348       1
..        ...     ...
14   2.890372       1
363  3.737670       1
304  3.688879       1
361  3.970292       1
329  3.850148       1

[80 rows x 2 columns]

In [34]:
y_test

Purchased
132          0
309          0
341          0
196          0
246          0
..         ...
14           0
363          0
304          0
361          1
329          1

[80 rows x 1 columns]

### Prediction

In [35]:
model.predict([[30, 0]])

c:\Users\ALICOM4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [38]:
model.predict([[30, 1]])

c:\Users\ALICOM4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [36]:
model.predict([[60, 1]])

c:\Users\ALICOM4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [37]:
model.predict([[60, 0]])

c:\Users\ALICOM4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [40]:
model.predict([[20, 0]])

c:\Users\ALICOM4\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

### Evaluation of Model

In [41]:
print('Training Score of Model =',model.score(x_train, y_train))
print('Testing Score of Model = ',model.score(x_test, y_test))

Training Score of Model = 0.840625
Testing Score of Model =  0.8
